using Discord.Interactions;
using System.Security.Cryptography;

namespace AdeptusDicus.Modules
{
    public class QuoteModule : InteractionModuleBase
    {
        private readonly Dictionary<int, string> _quotes = new()
            {
                { 1, "La seule récompense d’un lâche est de vivre dans la peur un jour de plus." },
                { 2, "Un poignard dans l’obscurité vaut mille épées à l’aube." },
                { 3, "Il est regrettable que nous ne puissions mourir qu’une seule fois au service de l’Empereur." },
                { 4, "Un esprit limité est un esprit ordonné." },
                { 5, "Un esprit suspicieux est un esprit sain." },
                { 6, "Une exécution rapide vaut mieux que cent interrogatoires." },
                { 7, "Exécrez le mutant." },
                { 8, "Abhorrez la Nuit, car c’est la Lumière qui perdure." },
                { 9, "Exécrez les xenos." },
                { 10, "La répulsion est un don; utilisez-le à bon escient." },
                { 11, "Visez sans pitié." },
                { 12, "Visez juste et frappez profondément." },
                { 13, "Toute vie mortelle est folie si elle ne nourrit pas l’esprit." },
                { 14, "Une opinion informée doit être rejetée avec la certitude résolue de la foi." },
                { 15, "Un esprit ouvert est comme une forteresse dont les portes sont ouvertes et non gardées." },
                { 16, "Levez-vous pour la vengeance." },
                { 17, "Ne soyez pas miséricordieux." },
                { 18, "Soyez ferme en défense." },
                { 19, "Soyez la faux de l’Empereur." },
                { 20, "Soyez le fléau des traîtres." },
                { 21, "Devenez la droiture incarnée." },
                { 22, "Devenez la vengeance." },
                { 23, "Méfiez-vous de la corruption de l’âme des hommes." },
                { 24, "Au-delà de la lumière de l’Empereur, il n’y a que désespoir." },
                { 25, "Bienheureux sont les intolérants." },
                { 26, "Bienheureux sont les impitoyables." },
                { 27, "Bienheureux sont ceux sans introspection, car ils ne connaîtront aucun doute." },
                { 28, "Béni soit le massacre des hérétiques." },
                { 29, "Béni soit le subjugateur." },
                { 30, "Béni soit le Dieu vengeur, car Il est le seul vrai Dieu." },
                { 31, "Béni soit le vengeur." },
                { 32, "Béni soit l’esprit trop petit pour douter." },
                { 33, "Béni soit ton tir." },
                { 34, "Béni soit ta fureur." },
                { 35, "Du sang pour le Dieu du Sang! Des crânes pour le Trône de Crânes!" },
                { 36, "Par leur mort, nous les reconnaîtrons." },
                { 37, "Par vos cicatrices et vos actes, vous serez jugés." },
                { 38, "Portez la Volonté de l’Empereur comme une torche dans les ténèbres." },
                { 39, "Portez vos cicatrices avec honneur." },
                { 40, "Purifiez le mutant; brûlez l’hérétique; purgez les xenos." },
                { 41, "Accrochez-vous à la lumière de l’Empereur." },
                { 42, "Se plaindre de ton sort est la première étape vers la Damnation." },
                { 43, "Condamnez les damnés à leur récompense." },
                { 44, "Le courage est le don de l’Empereur." },
                { 45, "Maudissez le traître, condamnez les faibles." },
                { 46, "La mort apporte la paix aux infidèles." },
                { 47, "Méprisez les faibles, car ils se rallieront à l’appel des renégats." },
                { 48, "Détruisez la corruption où qu’elle se trouve." },
                { 49, "Ne fuyez pas le combat désespéré, car l’effort est une récompense en soi." },
                { 50, "Ne doutez pas de la colère de l’Empereur." },
                { 51, "Ne doutez pas de votre force tant que la foi prévaut." },
                { 52, "Le devoir exige le sacrifice." },
                { 53, "Le devoir d’abord, le devoir en dernier." },
                { 54, "Le devoir est vital, la compréhension ne l’est pas." },
                { 55, "Que l’Empereur guide ton tir." },
                { 56, "Endurez le présent, afin que ceux qui vous suivent puissent poursuivre vos efforts." },
                { 57, "Même le plus grand héros n’est qu’une vague sur la surface de l’espace." },
                { 58, "Exister pour l’Empereur." },
                { 59, "Les faits sont des chaînes qui lient la perception et entravent la vérité." },
                { 60, "La foi conquiert tout." },
                { 61, "La foi n’a pas besoin d’excuse." },
                { 62, "Ne crains pas l’annihilation, car elle nous attend tous." },
                { 63, "Crains la colère des justes." },
                { 64, "Insensés sont ceux qui ne craignent rien, mais prétendent tout savoir." },
                { 65, "Pour chaque ennemi extérieur, il y en a cent à l’intérieur." },
                { 66, "N’oublie rien; ne pardonne rien." },
                { 67, "Le pardon est un crime punissable de mort." },
                { 68, "Le pardon est punissable de mort." },
                { 69, "Du devoir et de la mort, il n’y a aucun répit." },
                { 70, "Revêtez-vous de la lumière de l’Empereur." },
                { 71, "Gardez l’Humanité; craignez l’Ennemi d’Outre-Tombe." },
                { 72, "Gardez votre âme contre le désordre." },
                { 73, "Le bonheur est une illusion des faibles." },
                { 74, "Hâtez les damnés à leur récompense." },
                { 75, "Il sait ce qui se cache dans les ténèbres, et ne le craint pas." },
                { 76, "N’écoutez pas les murmures des infidèles." },
                { 77, "Écoutez la Parole de l’Empereur." },
                { 78, "Voici la fin des mutants." },
                { 79, "Ici s’achève ta leçon." },
                { 80, "Honore l’art de la mort." },
                { 81, "Honore ton Empereur." },
                { 82, "Honore tes serments, honore ton Empereur." },
                { 83, "Honore ton régiment." },
                { 84, "Honore ton arme." },
                { 85, "Honore ton devoir." },
                { 86, "Honneur, devoir et obéissance." },
                { 87, "L’espoir est superflu." },
                { 88, "L’espoir est la première étape vers la déception." },
                { 89, "J’apporte la mort." },
                { 90, "Je parle avec des langues de flammes." },
                { 91, "Si tu ne vois aucun signe de sédition, c’est que tu ne regardes pas assez attentivement" },
                { 92, "L’ignorance est ta meilleure défense." },
                { 93, "Imperialis Dominatus." },
                { 94, "L’impureté de l’acte ou de la pensée est une trahison." },
                { 95, "Dans la lumière de Terra, nous servons." },
                { 96, "L’innocence ne prouve rien." },
                { 97, "L’intolérance est une bénédiction." },
                { 98, "Il est un honneur de saigner pour l’Empereur." },
                { 99, "La justice ne tolère aucun doute." },
                { 100, "Garde la foi, tue l’ennemi." },
                { 101, "Tue l’hérétique avec ferveur." },
                { 102, "La connaissance nous rapproche de l’annihilation." },
                { 103, "La connaissance est un pouvoir, protège-la bien." },
                { 104, "Le manque de foi est équivalent à la trahison." },
                { 105, "Que la foi écrase la raison." },
                { 106, "Que nul ennemi ne se tienne devant toi." },
                { 107, "Que ta haine ne soit pas vaincue par la peur." },
                { 108, "Que ton arme soit le zèle et ton armure le mépris." },
                { 109, "La vie est éphémère ; le devoir est éternel." },
                { 110, "La vie n’est pas mesurée en années, mais par les actes des fidèles." },
                { 111, "La vie est la monnaie de l’Empereur, dépense-la avec sagesse." },
                { 112, "L’Humanité repose sur les épaules des martyrs." },
                { 113, "La miséricorde est une maladie ; l’intolérance en est le remède." },
                { 114, "Les esprits étroits sont des esprits fidèles." },
                { 115, "La nuit descend, mais la lumière de l’Empereur montre encore le chemin." },
                { 116, "Aucun homme n’est mort en service de l’Empereur en vain." },
                { 117, "Seule la mort met fin au devoir." },
                { 118, "Seul le lâche recherche le compromis." },
                { 119, "Rends jugement sans pitié." },
                { 120, "Persécute, punis, persiste." },
                { 121, "Loué soit l’Empereur, qui nous enseigne les voies de la guerre." },
                { 122, "Loué soit l’Empereur." },
                { 123, "++CENSURÉ PAR ORDRE DE L’INQUISITION++." },
                { 124, "Rejette la paix, car elle n’est qu’un mensonge." },
                { 125, "Réjouis-toi dans la repentance." },
                { 126, "Réjouis-toi dans ton service." },
                { 127, "La rétribution est ton droit de naissance." },
                { 128, "Parcours les étoiles au nom de l’Empereur." },
                { 129, "Cherche pour toi-même une mort digne de mémoire." },
                { 130, "Tuez les impurs et sanctifiez les fidèles." },
                { 131, "Frappe tous ceux qui s’opposent à l’Empereur." },
                { 132, "Frappe tous ceux qui oseraient souiller le nom de l’Empereur." },
                { 133, "Ne prononce pas les noms des traîtres." },
                { 134, "Ne souffre aucune impureté." },
                { 135, "La différence entre l’hérésie et la trahison est l’ignorance." },
                { 136, "L’Empereur porte le poids des maux de l’Humanité." },
                { 137, "L’Empereur nous accorde le don de l’intolérance." },
                { 138, "L’Empereur commande, l’Astra Militarum obéit." },
                { 139, "L’Empereur est tout." },
                { 140, "L’Empereur sait, l’Empereur observe." },
                { 141, "L’Empereur protège." },
                { 142, "La justice de l’Empereur est une chose magnifique." },
                { 143, "La culpabilité de l’hérésie pèse lourd sur l’âme." },
                { 144, "L’Imperium de l’Humanité ne cédera jamais." },
                { 145, "Le mutant est perfide, ne lui fais pas confiance." },
                { 146, "Le prix du devoir est élevé, mais les récompenses sont éternelles." },
                { 147, "Les justes ne craignent rien." },
                { 148, "Le même marteau qui brise le verre forge l’acier." },
                { 149, "Les graines de l’hérésie sont plantées dans les esprits éclairés." },
                { 150, "Le bouclier de la foi est ta meilleure protection." },
                { 151, "Le traître brûlera." },
                { 152, "La main du traître est plus proche que tu ne le penses." },
                { 153, "La vérité est terrible à supporter." },
                { 154, "Le vainqueur vit dans l’honneur ; le vaincu meurt dans la honte." },
                { 155, "Le salaire de la négligence est la destruction totale." },
                { 156, "Les faibles seront purgés, les forts endureront." },
                { 157, "La Volonté de l’Empereur est la puissance de l’Imperium." },
                { 158, "Les sages ont beaucoup à craindre ; les ignorants sont bénis par le courage." },
                { 159, "Les sages apprennent de la mort des autres." },
                { 160, "Il n’y a pas de murs assez solides pour protéger les ennemis de l’Humanité." },
                { 161, "Il n’existe pas d’être aussi vil que le traître." },
                { 162, "Il n’y a pas de peur dans la conviction." },
                { 163, "Il n’y a pas d’avenir sans la bénédiction de l’Empereur." },
                { 164, "Il n’y a que l’Empereur." },
                { 165, "Il y a une pureté de but dans la foi des justes." },
                { 166, "Tu es le marteau de l’Empereur." },
                { 167, "Tu seras rappelé par tes actes." },
                { 168, "Tu dois tuer." },
                { 169, "Tu ne céderas pas." },
                { 170, "Ta main est justice." },
                { 171, "La timidité engendre l’indécision ; l’indécision engendre la trahison." },
                { 172, "Se tromper, c’est inviter la rétribution." },
                { 173, "Abandonner le mépris, c’est capituler." },
                { 174, "Épargner le traître, c’est inviter la corruption." },
                { 175, "Questionner, c’est douter." },
                { 176, "Questionner ton maître, c’est trahir l’Empereur." },
                { 177, "Se retirer avec dégoût n’est pas de l’apathie." },
                { 178, "La tolérance engendre l’hérésie." },
                { 179, "La vraie foi est aveugle et justifiée." },
                { 180, "La vraie sagesse, c’est d’accepter l’inévitable." },
                { 181, "N’aie confiance qu’en l’Empereur." },
                { 182, "La vérité engendre la haine." },
                { 183, "Comprendre affaiblit la volonté d’agir." },
                { 184, "La victoire appartient à l’Empereur." },
                { 185, "La victoire n’a pas besoin d’explication ; la défaite n’en permet aucune." },
                { 186, "La guerre appelle: répondras-tu ?" },
                { 187, "Pèse le poing qui abat les hommes et salue la bataille gagnée." },
                { 188, "Accueille le jugement de l’Empereur." },
                { 189, "Sans peur ni hésitation, fais ton devoir." },
                { 190, "Résiste aux vents du chaos, car la lumière de l’Empereur brille à travers eux." },
                { 191, "Tu n’as pas besoin de comprendre pour accomplir ton devoir." },
                { 192, "Ton honneur est ta vie.Que nul ne le conteste." }
            };

        [SlashCommand("quote", "Citation de WarHammer40k : Dark Tide")]
        public async Task QuoteAsync()
        {
            var index = RandomNumberGenerator.GetInt32(0, _quotes.Count);
            await RespondAsync(_quotes[index]);
        }
        
    }
}
