//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdeptusDicus.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Quotes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Quotes() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdeptusDicus.Resources.Quotes", typeof(Quotes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A coward&apos;s only reward is to live in fear another day.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abhorrence is a gift; use it well.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep the faith, kill the foe.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kill the heretic with fervour.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Knowledge brings us closer to annihilation.
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Knowledge is power, guard it well.
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lack of faith is tantamount to treason.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Let faith trample reason.
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Let no foe stand before you.
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Let not thy hate be conquered by fear.
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Let thy weapon be zeal, and thy armour contempt.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Life is fleeting; duty is eternal.
        /// </summary>
        internal static string _109 {
            get {
                return ResourceManager.GetString("109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aim without mercy.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Life is measured not in years, but by the deeds of the faithful.
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Life is the Emperor&apos;s currency, spend it well.
        /// </summary>
        internal static string _111 {
            get {
                return ResourceManager.GetString("111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mankind stands upon the shoulders of the martyred.
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mercy is a disease; intolerance is the cure.
        /// </summary>
        internal static string _113 {
            get {
                return ResourceManager.GetString("113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Narrow minds are faithful minds.
        /// </summary>
        internal static string _114 {
            get {
                return ResourceManager.GetString("114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Night descends, yet still the Emperor&apos;s light shows the way.
        /// </summary>
        internal static string _115 {
            get {
                return ResourceManager.GetString("115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No man died in the Emperor&apos;s service that died in vain.
        /// </summary>
        internal static string _116 {
            get {
                return ResourceManager.GetString("116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only in death does duty end.
        /// </summary>
        internal static string _117 {
            get {
                return ResourceManager.GetString("117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only the coward seeks compromise.
        /// </summary>
        internal static string _118 {
            get {
                return ResourceManager.GetString("118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pass judgement without mercy.
        /// </summary>
        internal static string _119 {
            get {
                return ResourceManager.GetString("119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aim true and strike deep.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Persecute, punish, persist.
        /// </summary>
        internal static string _120 {
            get {
                return ResourceManager.GetString("120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Praise be the Emperor, who teaches us the ways of war.
        /// </summary>
        internal static string _121 {
            get {
                return ResourceManager.GetString("121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Praise the Emperor.
        /// </summary>
        internal static string _122 {
            get {
                return ResourceManager.GetString("122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ++REDACTED BY ORDER OF THE INQUISITION++.
        /// </summary>
        internal static string _123 {
            get {
                return ResourceManager.GetString("123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reject peace for the lie that it is.
        /// </summary>
        internal static string _124 {
            get {
                return ResourceManager.GetString("124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejoice in repentance.
        /// </summary>
        internal static string _125 {
            get {
                return ResourceManager.GetString("125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejoice in thy service.
        /// </summary>
        internal static string _126 {
            get {
                return ResourceManager.GetString("126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retribution is your birthright.
        /// </summary>
        internal static string _127 {
            get {
                return ResourceManager.GetString("127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scourge the stars in the Emperor&apos;s name.
        /// </summary>
        internal static string _128 {
            get {
                return ResourceManager.GetString("128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seek for yourself a death worthy of remembrance.
        /// </summary>
        internal static string _129 {
            get {
                return ResourceManager.GetString("129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All mortal life is folly that does not feed the spirit.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slay the impure and sanctify the faithful.
        /// </summary>
        internal static string _130 {
            get {
                return ResourceManager.GetString("130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smite all who oppose the Emperor.
        /// </summary>
        internal static string _131 {
            get {
                return ResourceManager.GetString("131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smite all who would besmirch the Emperor&apos;s name.
        /// </summary>
        internal static string _132 {
            get {
                return ResourceManager.GetString("132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speak not the names of traitors.
        /// </summary>
        internal static string _133 {
            get {
                return ResourceManager.GetString("133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suffer no impurity.
        /// </summary>
        internal static string _134 {
            get {
                return ResourceManager.GetString("134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The difference between heresy and treachery is ignorance.
        /// </summary>
        internal static string _135 {
            get {
                return ResourceManager.GetString("135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Emperor bears the weight of Mankind&apos;s ills.
        /// </summary>
        internal static string _136 {
            get {
                return ResourceManager.GetString("136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Emperor bestows upon us the gift of intolerance.
        /// </summary>
        internal static string _137 {
            get {
                return ResourceManager.GetString("137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Emperor commands, the Astra Militarum obeys.
        /// </summary>
        internal static string _138 {
            get {
                return ResourceManager.GetString("138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Emperor is all.
        /// </summary>
        internal static string _139 {
            get {
                return ResourceManager.GetString("139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An informed opinion must be dismissed with the resolute certainty of faith.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Emperor knows, the Emperor is watching.
        /// </summary>
        internal static string _140 {
            get {
                return ResourceManager.GetString("140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Emperor protects.
        /// </summary>
        internal static string _141 {
            get {
                return ResourceManager.GetString("141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Emperor&apos;s justice is a beautiful thing.
        /// </summary>
        internal static string _142 {
            get {
                return ResourceManager.GetString("142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The guilt of heresy weighs heavy on the soul.
        /// </summary>
        internal static string _143 {
            get {
                return ResourceManager.GetString("143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Imperium of Mankind shall never yield.
        /// </summary>
        internal static string _144 {
            get {
                return ResourceManager.GetString("144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The mutant is guileful, trust it not.
        /// </summary>
        internal static string _145 {
            get {
                return ResourceManager.GetString("145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The price of duty is high, but the rewards are eternal.
        /// </summary>
        internal static string _146 {
            get {
                return ResourceManager.GetString("146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The righteous fear naught.
        /// </summary>
        internal static string _147 {
            get {
                return ResourceManager.GetString("147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The same hammer that shatters the glass, forges the steel.
        /// </summary>
        internal static string _148 {
            get {
                return ResourceManager.GetString("148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The seeds of heresy are planted in the minds of the enlightened.
        /// </summary>
        internal static string _149 {
            get {
                return ResourceManager.GetString("149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An open mind is like a fortress with its gates unbarred and unguarded.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The shield of faith is your best protection.
        /// </summary>
        internal static string _150 {
            get {
                return ResourceManager.GetString("150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The traitor shall burn.
        /// </summary>
        internal static string _151 {
            get {
                return ResourceManager.GetString("151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The traitor&apos;s hand lies closer than you think.
        /// </summary>
        internal static string _152 {
            get {
                return ResourceManager.GetString("152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The truth is terrible to bear.
        /// </summary>
        internal static string _153 {
            get {
                return ResourceManager.GetString("153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The victor lives in honour; the vanquished dies in shame.
        /// </summary>
        internal static string _154 {
            get {
                return ResourceManager.GetString("154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The wage of negligence is utter destruction.
        /// </summary>
        internal static string _155 {
            get {
                return ResourceManager.GetString("155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The weak shall be purged, the strong shall endure.
        /// </summary>
        internal static string _156 {
            get {
                return ResourceManager.GetString("156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Will of the Emperor is the might of the Imperium.
        /// </summary>
        internal static string _157 {
            get {
                return ResourceManager.GetString("157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The wise have much to fear; the ignorant are blessed with courage.
        /// </summary>
        internal static string _158 {
            get {
                return ResourceManager.GetString("158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The wise learn from the deaths of others.
        /// </summary>
        internal static string _159 {
            get {
                return ResourceManager.GetString("159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arise for vengeance.
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are no walls strong enough to protect the enemies of Mankind.
        /// </summary>
        internal static string _160 {
            get {
                return ResourceManager.GetString("160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no being so foul as the traitor.
        /// </summary>
        internal static string _161 {
            get {
                return ResourceManager.GetString("161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no fear in conviction.
        /// </summary>
        internal static string _162 {
            get {
                return ResourceManager.GetString("162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no future without the Emperor&apos;s blessing.
        /// </summary>
        internal static string _163 {
            get {
                return ResourceManager.GetString("163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is only the Emperor.
        /// </summary>
        internal static string _164 {
            get {
                return ResourceManager.GetString("164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is purity of purpose in the faith of the just.
        /// </summary>
        internal static string _165 {
            get {
                return ResourceManager.GetString("165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thou art the hammer of the Emperor.
        /// </summary>
        internal static string _166 {
            get {
                return ResourceManager.GetString("166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thou shalt be remembered by thy deeds.
        /// </summary>
        internal static string _167 {
            get {
                return ResourceManager.GetString("167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thou shalt kill.
        /// </summary>
        internal static string _168 {
            get {
                return ResourceManager.GetString("168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thou shalt not yield.
        /// </summary>
        internal static string _169 {
            get {
                return ResourceManager.GetString("169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be not merciful.
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thy hand is justice.
        /// </summary>
        internal static string _170 {
            get {
                return ResourceManager.GetString("170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timidity begets indecision; indecision begets treachery.
        /// </summary>
        internal static string _171 {
            get {
                return ResourceManager.GetString("171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To err is to invite retribution.
        /// </summary>
        internal static string _172 {
            get {
                return ResourceManager.GetString("172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To relinquish contempt is capitulation.
        /// </summary>
        internal static string _173 {
            get {
                return ResourceManager.GetString("173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To spare the traitor is to invite corruption.
        /// </summary>
        internal static string _174 {
            get {
                return ResourceManager.GetString("174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To question is to doubt.
        /// </summary>
        internal static string _175 {
            get {
                return ResourceManager.GetString("175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To question your master is to betray the Emperor.
        /// </summary>
        internal static string _176 {
            get {
                return ResourceManager.GetString("176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To withdraw in disgust is not apathy.
        /// </summary>
        internal static string _177 {
            get {
                return ResourceManager.GetString("177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tolerance begets heresy.
        /// </summary>
        internal static string _178 {
            get {
                return ResourceManager.GetString("178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à True faith is blind and justified.
        /// </summary>
        internal static string _179 {
            get {
                return ResourceManager.GetString("179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be steadfast in defence.
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à True wisdom is acceptance of the inevitable.
        /// </summary>
        internal static string _180 {
            get {
                return ResourceManager.GetString("180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trust only the Emperor.
        /// </summary>
        internal static string _181 {
            get {
                return ResourceManager.GetString("181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Truth begets hatred.
        /// </summary>
        internal static string _182 {
            get {
                return ResourceManager.GetString("182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Understanding weakens the will to act.
        /// </summary>
        internal static string _183 {
            get {
                return ResourceManager.GetString("183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Victory belongs to the Emperor.
        /// </summary>
        internal static string _184 {
            get {
                return ResourceManager.GetString("184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Victory needs no explanation; defeat allows none.
        /// </summary>
        internal static string _185 {
            get {
                return ResourceManager.GetString("185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à War calls: will you answer?.
        /// </summary>
        internal static string _186 {
            get {
                return ResourceManager.GetString("186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weigh the fist that strikes men down and salutes the battle won.
        /// </summary>
        internal static string _187 {
            get {
                return ResourceManager.GetString("187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome the judgement of the Emperor.
        /// </summary>
        internal static string _188 {
            get {
                return ResourceManager.GetString("188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Without fear or falter, do thy duty.
        /// </summary>
        internal static string _189 {
            get {
                return ResourceManager.GetString("189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be the Emperor&apos;s reaper.
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Withstand the winds of chaos, for the Emperor&apos;s light shines through.
        /// </summary>
        internal static string _190 {
            get {
                return ResourceManager.GetString("190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need understand nothing to do your duty.
        /// </summary>
        internal static string _191 {
            get {
                return ResourceManager.GetString("191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your honor is your life. Let none dispute it.
        /// </summary>
        internal static string _192 {
            get {
                return ResourceManager.GetString("192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A dagger in the dark is worth a thousand swords at dawn.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be thou the scourge of traitors.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Become righteousness made manifest.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Become vengeance.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beware the corruption of men&apos;s souls.
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beyond the Emperor&apos;s light lies only despair.
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed are the intolerant.
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed are the merciless.
        /// </summary>
        internal static string _26 {
            get {
                return ResourceManager.GetString("26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed are they without introspection, for they shall know no doubt.
        /// </summary>
        internal static string _27 {
            get {
                return ResourceManager.GetString("27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed be the slaughterer of heretics.
        /// </summary>
        internal static string _28 {
            get {
                return ResourceManager.GetString("28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed be the subjugator.
        /// </summary>
        internal static string _29 {
            get {
                return ResourceManager.GetString("29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A pity it is that we can die but once in the Emperor&apos;s service.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed be the vengeful God, for He is the only true God.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed be the vengeful.
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed is the mind too small for doubt.
        /// </summary>
        internal static string _32 {
            get {
                return ResourceManager.GetString("32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed be thy aim.
        /// </summary>
        internal static string _33 {
            get {
                return ResourceManager.GetString("33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blessed be thy fury.
        /// </summary>
        internal static string _34 {
            get {
                return ResourceManager.GetString("34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blood for the Blood God! Skulls for the Skull Throne.
        /// </summary>
        internal static string _35 {
            get {
                return ResourceManager.GetString("35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By the way of their death shall we know them.
        /// </summary>
        internal static string _36 {
            get {
                return ResourceManager.GetString("36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By your scars and deeds shall you be judged.
        /// </summary>
        internal static string _37 {
            get {
                return ResourceManager.GetString("37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carry the Will of the Emperor like a torch in the darkness.
        /// </summary>
        internal static string _38 {
            get {
                return ResourceManager.GetString("38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carry your scars with honour.
        /// </summary>
        internal static string _39 {
            get {
                return ResourceManager.GetString("39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A small mind is a tidy mind.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cleanse the mutant; burn the heretic; purge the xenos.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cleave to the Emperor&apos;s light.
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complaining of thy lot is the first step on the Road to Damnation.
        /// </summary>
        internal static string _42 {
            get {
                return ResourceManager.GetString("42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Condemn the damned to their reward.
        /// </summary>
        internal static string _43 {
            get {
                return ResourceManager.GetString("43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courage is the Emperor&apos;s gift.
        /// </summary>
        internal static string _44 {
            get {
                return ResourceManager.GetString("44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Curse the traitor, condemn the weak.
        /// </summary>
        internal static string _45 {
            get {
                return ResourceManager.GetString("45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Death brings peace to the unfaithful.
        /// </summary>
        internal static string _46 {
            get {
                return ResourceManager.GetString("46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Despise the weak, for they shall flock to the call of the renegade.
        /// </summary>
        internal static string _47 {
            get {
                return ResourceManager.GetString("47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destroy the corruption wherever it is found.
        /// </summary>
        internal static string _48 {
            get {
                return ResourceManager.GetString("48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not shy the hopeless fight, for endeavour is its own reward.
        /// </summary>
        internal static string _49 {
            get {
                return ResourceManager.GetString("49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A suspicious mind is a healthy mind.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Doubt not the Emperor&apos;s wrath.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Doubt not thy strength whilst faith prevails.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duty demands sacrifice.
        /// </summary>
        internal static string _52 {
            get {
                return ResourceManager.GetString("52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duty first, duty last.
        /// </summary>
        internal static string _53 {
            get {
                return ResourceManager.GetString("53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duty is vital, understanding is not.
        /// </summary>
        internal static string _54 {
            get {
                return ResourceManager.GetString("54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emperor guide thy aim.
        /// </summary>
        internal static string _55 {
            get {
                return ResourceManager.GetString("55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endure the present, so those who follow may continue your endeavours.
        /// </summary>
        internal static string _56 {
            get {
                return ResourceManager.GetString("56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Even the greatest hero is but a ripple on the surface of space.
        /// </summary>
        internal static string _57 {
            get {
                return ResourceManager.GetString("57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exist for the Emperor.
        /// </summary>
        internal static string _58 {
            get {
                return ResourceManager.GetString("58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facts are chains that bind perception and fetter truth.
        /// </summary>
        internal static string _59 {
            get {
                return ResourceManager.GetString("59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A swift execution is worth a hundred interrogations.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faith conquers all.
        /// </summary>
        internal static string _60 {
            get {
                return ResourceManager.GetString("60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faith needs no excuse.
        /// </summary>
        internal static string _61 {
            get {
                return ResourceManager.GetString("61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fear not obliteration, for it awaits us all.
        /// </summary>
        internal static string _62 {
            get {
                return ResourceManager.GetString("62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fear the wrath of the righteous.
        /// </summary>
        internal static string _63 {
            get {
                return ResourceManager.GetString("63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Foolish are those who fear nothing, yet claim to know everything.
        /// </summary>
        internal static string _64 {
            get {
                return ResourceManager.GetString("64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For every enemy without, there are a hundred within.
        /// </summary>
        internal static string _65 {
            get {
                return ResourceManager.GetString("65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forget not; forgive nothing.
        /// </summary>
        internal static string _66 {
            get {
                return ResourceManager.GetString("66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgiveness is a crime punishable by death.
        /// </summary>
        internal static string _67 {
            get {
                return ResourceManager.GetString("67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgiveness is punishable by death.
        /// </summary>
        internal static string _68 {
            get {
                return ResourceManager.GetString("68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à From duty and death there can be no respite.
        /// </summary>
        internal static string _69 {
            get {
                return ResourceManager.GetString("69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abhor the mutant.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gird thyself with the Emperor&apos;s light.
        /// </summary>
        internal static string _70 {
            get {
                return ResourceManager.GetString("70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guard Humanity; fear the Enemy Beyond.
        /// </summary>
        internal static string _71 {
            get {
                return ResourceManager.GetString("71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guard thy soul against disorder.
        /// </summary>
        internal static string _72 {
            get {
                return ResourceManager.GetString("72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Happiness is a delusion of the Weak.
        /// </summary>
        internal static string _73 {
            get {
                return ResourceManager.GetString("73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hasten the damned to their reward.
        /// </summary>
        internal static string _74 {
            get {
                return ResourceManager.GetString("74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à He knows what lies in the darkness, and fears it not.
        /// </summary>
        internal static string _75 {
            get {
                return ResourceManager.GetString("75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heed not the whispers of the faithless.
        /// </summary>
        internal static string _76 {
            get {
                return ResourceManager.GetString("76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heed the Word of the Emperor.
        /// </summary>
        internal static string _77 {
            get {
                return ResourceManager.GetString("77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Here be the doom of mutants.
        /// </summary>
        internal static string _78 {
            get {
                return ResourceManager.GetString("78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Here endeth thy lesson.
        /// </summary>
        internal static string _79 {
            get {
                return ResourceManager.GetString("79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abhor the Night, it is the Light that Endures.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honour the craft of death.
        /// </summary>
        internal static string _80 {
            get {
                return ResourceManager.GetString("80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honour thy Emperor.
        /// </summary>
        internal static string _81 {
            get {
                return ResourceManager.GetString("81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honour thy oaths, honour thy Emperor.
        /// </summary>
        internal static string _82 {
            get {
                return ResourceManager.GetString("82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honour thy regiment.
        /// </summary>
        internal static string _83 {
            get {
                return ResourceManager.GetString("83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honour thy weapon.
        /// </summary>
        internal static string _84 {
            get {
                return ResourceManager.GetString("84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honour your duty.
        /// </summary>
        internal static string _85 {
            get {
                return ResourceManager.GetString("85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honour, duty and obedience.
        /// </summary>
        internal static string _86 {
            get {
                return ResourceManager.GetString("86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hope is superfluous.
        /// </summary>
        internal static string _87 {
            get {
                return ResourceManager.GetString("87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hope is the first step on the road to disappointment.
        /// </summary>
        internal static string _88 {
            get {
                return ResourceManager.GetString("88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I bringeth death.
        /// </summary>
        internal static string _89 {
            get {
                return ResourceManager.GetString("89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abhor the xenos.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I speak with tongues of flame.
        /// </summary>
        internal static string _90 {
            get {
                return ResourceManager.GetString("90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you see no signs of sedition, you aren&apos;t looking hard enough.
        /// </summary>
        internal static string _91 {
            get {
                return ResourceManager.GetString("91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignorance is thy best defence.
        /// </summary>
        internal static string _92 {
            get {
                return ResourceManager.GetString("92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Imperialis Dominatus.
        /// </summary>
        internal static string _93 {
            get {
                return ResourceManager.GetString("93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impurity of deed or thought is treason.
        /// </summary>
        internal static string _94 {
            get {
                return ResourceManager.GetString("94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In Terra&apos;s light we serve.
        /// </summary>
        internal static string _95 {
            get {
                return ResourceManager.GetString("95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Innocence proves nothing.
        /// </summary>
        internal static string _96 {
            get {
                return ResourceManager.GetString("96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intolerance is a blessing.
        /// </summary>
        internal static string _97 {
            get {
                return ResourceManager.GetString("97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It is an honour to bleed for the Emperor.
        /// </summary>
        internal static string _98 {
            get {
                return ResourceManager.GetString("98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Justice allows no doubt.
        /// </summary>
        internal static string _99 {
            get {
                return ResourceManager.GetString("99", resourceCulture);
            }
        }
    }
}
